apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}
  replicas: ${K8S_REPLICAS}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - name: main
          image: harbor.cluster.home.sanlea.com/study/${APP_NAME}:${APP_VERSION}
          resources:
            requests:
              cpu: ${K8S_REQUEST_CPU}
              memory: ${K8S_REQUEST_MEMORY}
            limits:
              cpu: ${K8S_LIMIT_CPU}
              memory: ${K8S_LIMIT_MEMORY}
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always
