podTemplate(yaml:"""
kind: Pod
spec:
  serviceAccountName: jenkins-deployer
  containers:
  - name: kaniko
    image: harbor.infra.sanlea.com/infra/kaniko-executor:debug
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    volumeMounts:
      - name: registry-secret
        mountPath: /kaniko/.docker
      - name: maven-home
        mountPath: /home/jenkins
  - name: graalvm
    image: harbor.infra.sanlea.com/infra/graalvm-native-image:22.2.0
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    volumeMounts:
      - name: maven-home
        mountPath: /root/.m2
  - name: kubernetes
    image: harbor.infra.sanlea.com/infra/kubectl:1.24
    imagePullPolicy: IfNotPresent
    tty: true
    command:
    - cat
  volumes:
    - name: maven-home
      persistentVolumeClaim:
        claimName: maven-repo-storage
    - name: registry-secret
      secret:
        secretName: harbor-registry-client
        items:
          - key: .dockerconfigjson
            path: config.json
"""
  ) {
    node(POD_LABEL) {
        def version = new Date().format("yyyyMMddHHmmss")

        stage('Prepare') {
            currentBuild.displayName = version

            try {
                container('kubernetes') {
                    sh 'kubectl get deployments -n infra xxxx'
                    sh 'echo "hahahahahhah"'
                }
            } catch (e) {
                sh 'echo "hohohohohoh---->>>>>>>"'
            }
        }

        stage('Clone codes') {
            git url:params.GIT_URL, branch:params.GIT_BRANCH
            dir('tools') {
                git url:params.GIT_URL, branch:params.GIT_BRANCH
            }
            sh 'ls -l'
            sh 'ls tools'
        }

        stage('Build') {
            container('graalvm') {
                sh './mvnw clean'
                sh './mvnw package'
            }
        }

        stage('Build image') {
            container('kaniko') {
                sh "/kaniko/executor --skip-tls-verify --dockerfile=./src/main/docker/Dockerfile.jvm -c . --destination=harbor.infra.sanlea.com/kutzhang/${params.IMAGE_NAME}:${version}"
            }
        }

        stage('Deploy') {
            container('kubernetes') {
                sh 'kubectl get pod -n infra'
                sh 'kubectl get node -o wide'
            }
        }
    }
}